apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: ajwelch-x-app
spec:
  parentRefs:
    - name: gateway
      namespace: envoy-gateway-system
      kind: Gateway
      group: gateway.networking.k8s.io
  hostnames:
    - grafana.ajwelch-x-app.test
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          namespace: ajwelch-x-app
          kind: Service
          port: 3000
