---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: PLACEHOLDER
data:
  default.yaml: |
    apiVersion: 1

    datasources:
      - name: gdev-testdata
        isDefault: false
        type: testdata
