apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-plugins
  namespace: PLACEHOLDER
data:
  app.yaml: |
    apiVersion: 1

    apps:
      - type: 'ajwelch-x-app'
        org_id: 1
        org_name: 'aj-welch'
        disabled: false
        jsonData:
          apiUrl: http://default-url.com
          isApiKeySet: true
        secureJsonData:
          apiKey: secret-key
