apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ajwelch-x-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: localhost:5000/ajwelch-x-app:dev
          ports:
            - containerPort: 3000
            - containerPort: 2345
          env:
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: ajwelch-x-app
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_DEFAULT_APP_MODE
              value: development
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          volumeMounts:
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: provisioning-plugins
              mountPath: /etc/grafana/provisioning/plugins
      volumes:
        - name: provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources
        - name: provisioning-plugins
          configMap:
            name: grafana-provisioning-plugins
