---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-vars
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  IMAGE: PLACEHOLDER
  NAMESPACE: PLACEHOLDER
  PLUGIN_ID: PLACEHOLDER
