---
# This GitHub Action automates the process of building Grafana plugins.
name: Release

on:
  push:
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0.

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/build-plugin@build-plugin/v1.0.2
        # yamllint disable rule:comments-indentation
        # Uncomment to enable plugin signing
        # (For more info, see https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin)
        # with:
        # Make sure to save the token in your repository secrets
        # policy_token: $
        # Usage of GRAFANA_API_KEY is deprecated, prefer `policy_token` option above
        # grafana_token: $
        # yamllint enable rule:comments-indentation
